#!/usr/bin/env python3

if __name__ == "__main__":
    from liblax.parser import run
    from optparse import OptionParser
    import sys

    parser = OptionParser()
    parser.add_option(
        "-c", "--code", action="store", dest="code", help="Example: lax -c 'x ** 2 - 1'"
    )
    (opt, args) = parser.parse_args()

    if opt.code is None:
        parser.print_help()
        sys.exit("Error: no code provided!")

    print(run(opt.code))
